# Permissive limiter config - allow all internal requests

[botdetection.ip_limit]
# disable IP-based rate limiting
link_token = false

[botdetection.ip_lists]
# no blocked IPs
block_ip = []
pass_ip = [
  "0.0.0.0/0",
]
